from ClientEvents import *
from ClientRequests import *

# substate=state*10 + 0~9
STATE_AUTO=0
STATE_COMNAV=1
SUBSTATE_COM1=10
SUBSTATE_COM2=11
SUBSTATE_NAV1=12
SUBSTATE_NAV2=13

STATE_GPS=2

STATE_G1000=3
SUBSTATE_FMS=30
SUBSTATE_ALT=31
SUBSTATE_HDG_G1k=32
SUBSTATE_CRS=33
SUBSTATE_MFD=35

STATE_INST=5
SUBSTATE_HDG=50
SUBSTATE_OBS=51

STATE_LIGHT=6

STATE_END=7

# STATE  0~ max 9
# button 0~ max 9

statelabel=['AutoP','COM/NAV','GPS','G1000','','Instr','Light','','reset','quit']

buttonlabels={
    STATE_AUTO:['ap','hdg','nav','apr','rev','alt','','','','nav/gps'],
    STATE_COMNAV:['Com1','Com2','Nav1','Nav2','','audio','audio','audio','audio','stby'],
    
    STATE_GPS:['nrst','msg', '', '', '', 'dir','menu','clr','ent','clrall'],
    STATE_G1000:['FMS','ALT','HDG', 'CRS','','MFD'],
    STATE_INST:['hdg','obs'],
    STATE_LIGHT:['strobe','nav','taxi','land','panel'],
    }

buttonactions={
    STATE_AUTO:[AP_MASTER, AP_HDG_HOLD, AP_NAV1_HOLD, AP_APR_HOLD, AP_BC_HOLD, AP_ALT_HOLD, EVENT_NONE, EVENT_NONE, EVENT_NONE, TOGGLE_GPS_DRIVES_NAV1,],
    STATE_COMNAV:[EVENT_NONE,EVENT_NONE,EVENT_NONE,EVENT_NONE, EVENT_NONE,
                  COM1_TRANSMIT_SELECT,COM2_TRANSMIT_SELECT,RADIO_VOR1_IDENT_TOGGLE,RADIO_VOR2_IDENT_TOGGLE, EVENT_NONE],
    
    STATE_GPS :[GPS_NEAREST_BUTTON, GPS_MSG_BUTTON, EVENT_NONE, EVENT_NONE, EVENT_NONE, GPS_DIRECTTO_BUTTON, GPS_MENU_BUTTON, GPS_CLEAR_BUTTON, GPS_ENTER_BUTTON, GPS_CLEAR_ALL_BUTTON],
    STATE_LIGHT:[STROBES_TOGGLE,TOGGLE_NAV_LIGHTS,TOGGLE_TAXI_LIGHTS,LANDING_LIGHTS_TOGGLE,PANEL_LIGHTS_TOGGLE,],
    
    }
                

rotarytable={
    # button,  rotate right,  rotate left
    STATE_AUTO:[EVENT_NONE, AP_ALT_VAR_INC, AP_ALT_VAR_DEC],
    
    STATE_GPS:[GPS_CURSOR_BUTTON, GPS_GROUP_KNOB_INC, GPS_GROUP_KNOB_DEC],
    SUBSTATE_HDG:[EVENT_NONE, HEADING_BUG_INC, HEADING_BUG_DEC],
    SUBSTATE_OBS:[EVENT_NONE, VOR1_OBI_DEC, VOR1_OBI_INC],
    
    SUBSTATE_COM1:[COM_STBY_RADIO_SWAP, COM_RADIO_WHOLE_INC, COM_RADIO_WHOLE_DEC],
    SUBSTATE_COM2:[COM2_RADIO_SWAP, COM2_RADIO_WHOLE_INC, COM2_RADIO_WHOLE_DEC],
    SUBSTATE_NAV1:[NAV1_RADIO_SWAP, NAV1_RADIO_WHOLE_INC, NAV1_RADIO_WHOLE_DEC],
    SUBSTATE_NAV2:[NAV2_RADIO_SWAP, NAV2_RADIO_WHOLE_INC, NAV2_RADIO_WHOLE_DEC],
    
    SUBSTATE_FMS:[G1000_PFD_CURSOR_BUTTON, G1000_PFD_GROUP_KNOB_INC,G1000_PFD_GROUP_KNOB_DEC],
    SUBSTATE_ALT:[EVENT_NONE, AP_ALT_VAR_INC, AP_ALT_VAR_DEC],
    SUBSTATE_HDG_G1k:[REQ_HDGBUG_SYNC, HEADING_BUG_INC, HEADING_BUG_DEC],
    SUBSTATE_CRS:[EVENT_NONE, VOR1_OBI_INC, VOR1_OBI_DEC],
    SUBSTATE_MFD:[G1000_MFD_CURSOR_BUTTON, G1000_MFD_GROUP_KNOB_INC,G1000_MFD_GROUP_KNOB_DEC],
    }

rotarytable2={
    # button,  rotate right,  rotate left
    STATE_AUTO:[EVENT_NONE, AP_VS_VAR_INC, AP_VS_VAR_DEC],
    
    STATE_GPS:[GPS_CURSOR_BUTTON, GPS_PAGE_KNOB_INC, GPS_PAGE_KNOB_DEC],
    SUBSTATE_HDG:[EVENT_NONE, HEADING_BUG_INC, HEADING_BUG_DEC],
    SUBSTATE_OBS:[EVENT_NONE, VOR2_OBI_DEC, VOR2_OBI_INC],
    
    SUBSTATE_COM1:[COM_STBY_RADIO_SWAP, COM_RADIO_FRACT_INC, COM_RADIO_FRACT_DEC],
    SUBSTATE_COM2:[COM2_RADIO_SWAP, COM2_RADIO_FRACT_INC, COM2_RADIO_FRACT_DEC],
    SUBSTATE_NAV1:[NAV1_RADIO_SWAP, NAV1_RADIO_FRACT_INC, NAV1_RADIO_FRACT_DEC],
    SUBSTATE_NAV2:[NAV2_RADIO_SWAP, NAV2_RADIO_FRACT_INC, NAV2_RADIO_FRACT_DEC],
    
    SUBSTATE_FMS:[G1000_PFD_CURSOR_BUTTON, G1000_PFD_PAGE_KNOB_INC,G1000_PFD_PAGE_KNOB_DEC],
    SUBSTATE_ALT:[EVENT_NONE, AP_ALT_VAR_INC, AP_ALT_VAR_DEC],
    SUBSTATE_HDG_G1k:[REQ_HDGBUG_SYNC, HEADING_BUG_INC, HEADING_BUG_DEC],
    SUBSTATE_CRS:[EVENT_NONE, VOR2_OBI_INC, VOR2_OBI_DEC],
    SUBSTATE_MFD:[G1000_MFD_CURSOR_BUTTON, G1000_MFD_PAGE_KNOB_INC,G1000_MFD_PAGE_KNOB_DEC],
    }    
                
#request ids
request_ids={
    COM_RADIO_WHOLE_DEC:REQ_COM1_FREQ,
    COM_RADIO_WHOLE_INC:REQ_COM1_FREQ,
    COM_RADIO_FRACT_DEC:REQ_COM1_FREQ,
    COM_RADIO_FRACT_INC:REQ_COM1_FREQ,
    
    COM2_RADIO_WHOLE_DEC:REQ_COM2_FREQ,
    COM2_RADIO_WHOLE_INC:REQ_COM2_FREQ,
    COM2_RADIO_FRACT_DEC:REQ_COM2_FREQ,
    COM2_RADIO_FRACT_INC:REQ_COM2_FREQ,
    
    NAV1_RADIO_WHOLE_DEC:REQ_NAV1_FREQ,
    NAV1_RADIO_WHOLE_INC:REQ_NAV1_FREQ,
    NAV1_RADIO_FRACT_DEC:REQ_NAV1_FREQ,
    NAV1_RADIO_FRACT_INC:REQ_NAV1_FREQ,
    
    NAV2_RADIO_WHOLE_DEC:REQ_NAV2_FREQ,
    NAV2_RADIO_WHOLE_INC:REQ_NAV2_FREQ,
    NAV2_RADIO_FRACT_DEC:REQ_NAV2_FREQ,
    NAV2_RADIO_FRACT_INC:REQ_NAV2_FREQ,

    AP_MASTER:REQ_AP_STATUS,
    AP_HDG_HOLD:REQ_AP_STATUS,
    AP_NAV1_HOLD:REQ_AP_STATUS,
    AP_APR_HOLD:REQ_AP_STATUS,
    AP_BC_HOLD:REQ_AP_STATUS,
    AP_ALT_HOLD:REQ_AP_STATUS,
    
    
    }
